batch_size: 128
beta_annealing_activated: true
beta_annealing_per_cycle_period: 25
beta_annealing_per_cycle_rising_ratio: 0.5
beta_annealing_start_first_rise_at_epoch: 5
beta_level: 0.5
d_model_dec: 128
d_model_enc: 16
dataset_json_dir: "data/dataset_json_settings"
dataset_json_fname: "Balanced_6000_performed.json"
device: "cuda"
dim_feedforward_dec: 512
dim_feedforward_enc: 16
dropout: 0.1
embedding_size_src: 3
embedding_size_tgt: 27
epochs: 1000
is_testing: false
latent_dim: 128
lr: 0.0006369948608989782
max_len_dec: 32
max_len_enc: 32
n_genres: 9      # Only used for MuteGenreLatentVAE
n_global_density_bins: 10
nhead_dec: 8
nhead_enc: 4
num_decoder_layers: 7
num_encoder_layers: 3
offset_dropout: 0
optimizer: "adam"
velocity_dropout: 0
scale_h_loss: 1
scale_v_loss: 4
scale_o_loss: 10
