dataset_root_path: "data/triple_streams/model_ready/AccentAt0.75/"

dataset_files:
    - "01_candombe_four_voices.pkl.bz2"
    - "03_groove_midi_crash_hhclosed_hhopen_ride.pkl.bz2"
    - "04_groove_midi_hh_kick_snare_toms.pkl.bz2"
    - "05_groove_midi_hi_lo_mid_ride.pkl.bz2"
    - "06_lmd_bass_brass_drum_percussion.pkl.bz2"
    - "07_lmd_bass_brass_drum_percussive.pkl.bz2"
    - "08_lmd_bass_brass_guitar_percussion.pkl.bz2"
    - "09_lmd_bass_brass_guitar_percussive.pkl.bz2"
    - "10_lmd_bass_brass_guitar_piano.pkl.bz2"
    - "11_lmd_bass_brass_percussion_percussive.pkl.bz2"
    - "12_lmd_bass_brass_percussion_piano.pkl.bz2"
    - "13_lmd_bass_brass_percussive_piano.pkl.bz2"
    - "14_lmd_bass_drum_guitar_percussion.pkl.bz2"
    - "15_lmd_bass_drum_guitar_percussive.pkl.bz2"
    - "16_lmd_bass_drum_percussion_percussive.pkl.bz2"
    - "17_lmd_bass_drum_percussion_piano.pkl.bz2"
    - "18_lmd_bass_drum_percussive_piano.pkl.bz2"
    - "19_lmd_bass_guitar_percussion_percussive.pkl.bz2"
    - "20_lmd_bass_guitar_percussion_piano.pkl.bz2"
    - "21_lmd_bass_guitar_percussive_piano.pkl.bz2"
    - "22_lmd_bass_percussion_percussive_piano.pkl.bz2"
    - "23_lmd_brass_drum_guitar_percussion.pkl.bz2"
    - "24_lmd_brass_drum_guitar_percussive.pkl.bz2"
    - "25_lmd_brass_drum_guitar_piano.pkl.bz2"
    - "26_lmd_brass_drum_percussion_percussive.pkl.bz2"
    - "27_lmd_brass_drum_percussion_piano.pkl.bz2"
    - "28_lmd_brass_drum_percussive_piano.pkl.bz2"
    - "29_lmd_brass_guitar_percussion_percussive.pkl.bz2"
    - "30_lmd_brass_guitar_percussion_piano.pkl.bz2"
    - "31_lmd_brass_guitar_percussive_piano.pkl.bz2"
    - "32_lmd_brass_percussion_percussive_piano.pkl.bz2"
    - "33_lmd_drum_guitar_percussion_percussive.pkl.bz2"
    - "34_lmd_drum_guitar_percussion_piano.pkl.bz2"
    - "35_lmd_drum_guitar_percussive_piano.pkl.bz2"
    - "36_lmd_drum_percussion_percussive_piano.pkl.bz2"
    - "37_lmd_guitar_percussion_percussive_piano.pkl.bz2"
    - "38_ttd_both-is-and_both_flattened_left_right.pkl.bz2"
    - "39_ttd_both-is-or_both_flattened_left_right.pkl.bz2"

encoding_control1_key: "Flat Out Vs. Input | Hits | Hamming"
encoding_control2_key: "Flat Out Vs. Input | Accent | Hamming"
decoding_control1_key: "Stream 1 Vs. Flat Out | Hits | Hamming"
decoding_control2_key: "Stream 2 Vs. Flat Out | Hits | Hamming"
decoding_control3_key: "Stream 3 Vs. Flat Out | Hits | Hamming"

n_encoding_control1_tokens: 33
n_encoding_control2_tokens: 10
n_decoding_control1_tokens: 10
n_decoding_control2_tokens: 10
n_decoding_control3_tokens: 10

max_len: 32

batch_size: 256
beta_annealing_activated: true
beta_annealing_per_cycle_period: 25
beta_annealing_per_cycle_rising_ratio: 0.5
beta_annealing_start_first_rise_at_epoch: 5
beta_level: 0.2
d_model_dec: 128
d_model_enc: 64

dim_feedforward_dec: 512
dim_feedforward_enc: 128
dropout: 0.1
embedding_size_src: 3
embedding_size_tgt: 9
epochs: 1000
is_testing: false
latent_dim: 128
lr: 0.0006369948608989782

nhead_dec: 8
nhead_enc: 8
num_decoder_layers: 12
num_encoder_layers: 7
offset_dropout: 0
optimizer: "adam"
velocity_dropout: 0
scale_h_loss: 1
scale_v_loss: 1
scale_o_loss: 1