dataset_root_path: "data/triple_streams/model_ready/AccentAt0.75/"

dataset_files:
    - "01_candombe_four_voices.pkl.bz2"
    - "38_ttd_both-is-and_both_flattened_left_right.pkl.bz2"
    - "39_ttd_both-is-or_both_flattened_left_right.pkl.bz2"

encoding_control1_key: "Flat Out Vs. Input | Hits | Hamming"
encoding_control2_key: "Flat Out Vs. Input | Accent | Hamming"
decoding_control1_key: "Stream 1 Vs. Flat Out | Hits | Hamming"
decoding_control2_key: "Stream 2 Vs. Flat Out | Hits | Hamming"
decoding_control3_key: "Stream 3 Vs. Flat Out | Hits | Hamming"

n_encoding_control1_tokens: 33
n_encoding_control2_tokens: 10
n_decoding_control1_tokens: 10
n_decoding_control2_tokens: 10
n_decoding_control3_tokens: 10

max_len: 32

batch_size: 128
beta_annealing_activated: true
beta_annealing_per_cycle_period: 25
beta_annealing_per_cycle_rising_ratio: 0.5
beta_annealing_start_first_rise_at_epoch: 5
beta_level: 0.5
d_model_dec: 128
d_model_enc: 16

dim_feedforward_dec: 512
dim_feedforward_enc: 16
dropout: 0.1
embedding_size_src: 3
embedding_size_tgt: 9
epochs: 1000
is_testing: true
latent_dim: 128
lr: 0.0006369948608989782

nhead_dec: 8
nhead_enc: 4
num_decoder_layers: 7
num_encoder_layers: 3
offset_dropout: 0
optimizer: "adam"
velocity_dropout: 0
scale_h_loss: 1
scale_v_loss: 4
scale_o_loss: 10